### PR TITLE
Allow drivers with variant 1 (vksc) in VKSC builds

### PR DESCRIPTION
**Pull request by zangold**

### CODE REVIEW

**Comment by aqnuep** [comment]
Hi @zangold!

It seems that this PR assumes some undocumented functionality related to the `api_version` field of the ICD JSON files.

Apparently, the loader code does not only support the format `<major>.<minor>.<patch>`, but also `<variant>.<major>.<minor>.<patch>` when parsing the version string. This second format is what this PR assumes, and something that the loader has some supporting code for, but was never actually exercised AFAICT.

FWIW, we currently only support and test the API version format without a variant prefix. This is what all the JSON files always contained (i.e. currently `1.0.14`):

- `VkICD_mock_icd_vksc.json` for the Mock ICD
- `VkSCLayer_khronos_validation.json` for the validation layers
- `VkSCLayer_khronos_device_simulation.json` for the device simulation layer

As such, I'd suggest to keep this instead of adopting an undocumented backward-incompatible API version format.

Honestly, I don't see why we would want to adopt a variant-prefixed format, considering that the Vulkan and Vulkan SC configuration files are in distinct locations, but if, for some reason, we'd like to also support such variant-prefixed formats, we would need the following actions:

- Document the alternative variant-prefixed format
- Update all ecosystem components to adopt it and test it
- Keep supporting the current "simple" API version format for backward-compatibility

Could you please clarify the motivation behind suggesting this change?

**Comment by zangold** [comment]
Hi @aqnuep, thanks for taking a look at my patch!

I pulled from sc_main (I was previously on a version from mid-December) and tried to test my changes locally. The behaviour of the loader changed since then, and I found that the API version being sent to the driver (in vkCreateInstance) was the same version as specified in api_version in the driver JSON file. Since that version is 1.0.0, and the driver version is 1.1.0.0 (i.e., API variant 1, version 1.0.0), this caused the driver to return VK_ERROR_INCOMPATIBLE_DRIVER from vkCreateInstance. So, I changed the version string (api_version) in the driver JSON to 1.1.0.0. The loader rejected this, so I made the change above in order to force the loader to only recognize drivers/layers with an API variant that matches the API variant the loader was built with.

It seems as though all of the tests are coded to use API variant 0, which appears to be causing the failures in the automated checks.

I suppose another fix would be for the loader (with VULKANSC=ON) to edit the version string in the JSON files it reads to change them to API variant 1, but I thought my approach might help to prevent (or at least clarify) bugs where the SC loader tries to load a non-SC driver (or non-SC loader tries to load an SC driver).

**Comment by zangold** [comment]
I just confirmed locally that changing loader_parse_version_string to initialize variant to 1 for VKSC (0 for non-SC) fixes the problems with the tests (at least, on win64 for both -DVULKANSC={ON,OFF}), still works for my purposes, and allows me to specify version 1.0.0 in my vksc.json file without the driver complaining about an unsupported version.

I'll push my change here to get the expanded coverage from the CI builds.

**Comment by aqnuep** [comment]
Also, I'd note that I'm surprised this is causing issues on implementations, considering that the Vulkan SC Mock ICD is also reporting an API version with the Vulkan SC API variant, yet it does load just fine as we have extensive testing infrastructure relying on it.

**Comment by dgkoch** [comment]
> Second, I'd like to understand why LunarG has added support for the `<variant>.<major>.<minor>.<patch>` format, as it's not something that has ever been officially supported or discussed with the Vulkan SC WG, AFAICT. So I'd like to figure out the motivation and history so that we can update the implementation accordingly.
> 
> @dgkoch, do you know anything about this?

No, I'm not sure what's going on here. It might have been preliminary work for https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5046 ?

**Comment by aqnuep** [comment]
> I just confirmed locally that changing loader_parse_version_string to initialize variant to 1 for VKSC (0 for non-SC) fixes the problems with the tests (at least, on win64 for both -DVULKANSC={ON,OFF}), still works for my purposes, and allows me to specify version 1.0.0 in my vksc.json file without the driver complaining about an unsupported version.

@zangold, just to understand the whole situation. Does the latest code in `sc_main` fail to load the Vulkan SC driver you're testing with without your changes if the JSON contains version 1.0.x?

**Comment by zangold** [comment]
> @zangold, just to understand the whole situation. Does the latest code in sc_main fail to load the Vulkan SC driver you're testing with without your changes if the JSON contains version 1.0.x?

Yes: on sc_main, the loader replaces the API version in vkCreateInstance with the one found in the JSON, and if the JSON contains version 1.0.x, the loader will give the driver VK_MAKE_API_VERSION(0, 1, 0, x), which causes it to fail with VK_ERROR_INCOMPATIBLE_DRIVER.

**Comment by aqnuep** [comment]
> the loader will give the driver VK_MAKE_API_VERSION(0, 1, 0, x), which causes it to fail with VK_ERROR_INCOMPATIBLE_DRIVER.

Yes, that's the part which caused this to be undetected, as the Mock ICD does report the Vulkan SC API variant in the version (and passes the loader checks regarding that), but as it's a Mock ICD will ignore the input version at instance creation time. This is what caused this issue to go undetected.

I'll align a solution for this with upstream, fix it, and also find a way to cover it with additional testing, either using real Vulkan SC drivers, or adding some checks to the Mock ICD itself.

**Comment by aqnuep** [comment]
@zangold, for now, could you please verify the code in this branch?

https://github.com/KhronosGroup/VulkanSC-Loader/tree/icd-variant-fix

I think that is the minimal sufficient change to get this fixed and not have other unintended side effects (as, funny enough, the `loader_parse_version_string` function is used for other version loading that aren't even Vulkan or Vulkan SC API versions, like the version of the manifest file format itself, so having the variant there never really made much sense). I'll put together a final, tested solution later, just want to confirm that this resolves your problems.

**Comment by zangold** [comment]
Just verified the icd-variant-fix branch, and it seems to work for my purposes. Should I close this PR?

**Comment by aqnuep** [comment]
> Just verified the icd-variant-fix branch, and it seems to work for my purposes. Should I close this PR?

Feel free to do so. I'll create a sufficient repro case to make sure that it does not regress and will get the fix merged into sc_main.
Thank you and sorry about the inconvenience this caused.

**Comment by aqnuep** [comment]
@zangold, I just have one more request.

Could you please send me the entire `VkInstanceCreateInfo` (including the `VkApplicationInfo`) structure you saw the issue with?

I'm still unable to reproduce the issue of missing variant sent to the ICD without the fix, so I'm still unclear what scenario this could happen in.

**Comment by zangold** [comment]
> Feel free to do so. I'll create a sufficient repro case to make sure that it does not regress and will get the fix merged into sc_main.

Thanks! There's a bit more info below that might be relevant, so I'll hold off on closing this until this issue is sorted out.

> Could you please send me the entire VkInstanceCreateInfo (including the VkApplicationInfo) structure you saw the issue with?

Sure. At the start of vkCreateInstance (as defined by the loader), the structure is:

pCreateInfo->sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
pCreateInfo->pApplicationInfo->sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
pCreateInfo->pApplicationInfo->pApplicationName = "deqp";
pCreateInfo->pApplicationInfo->applicationVersion = 1298041715;
pCreateInfo->pApplicationInfo->pEngineName = "deqp";
pCreateInfo->pApplicationInfo->engineVersion = 1298041715;
pCreateInfo->pApplicationInfo->apiVersion = 0x20400000; // VulkanSC 1.0.0

The rest of the fields in VkInstanceCreateInfo and VkApplicationInfo were all zero, so I've removed them for brevity.

... After doing some more investigation, I can't reproduce the error locally on sc_main (most recent commit Wed Jan 10, gcid 6c304c20772994fe7bff5d18c8f41d466a3bfed5). I think this behaviour is because of the previous commit on sc_main (1c39170d216b179557067a6c7c1b57e9cd69f665) which I believe I didn't have at the time I was writing the code for this PR.

I synced to the git commit just before that one (23a4d004ccffc3a3d3fd03b4865837eeec482046) and I can reproduce the issue again!

At this point in VulkanSC-Loader history, what happens is (in the block in terminator_CreateInstance that computes icd_version):
- icd_version is initialized to VK_API_VERSION_1_0
- icd_term->scanned_icd->api_version >= VK_API_VERSION_1_1 evaluates to false (because the version string has no variant value, so it's equal to VK_API_VERSION_1_0), so the if-block is never executed
- just a couple lines above the call into the ICD vkCreateInstance in the same function, icd_app_info.apiVersion is set to icd_version,  which is still the same value it was initialized with (VK_API_VERSION_1_0)

As of today's sc_main (or, at least, the one with the commit from Jan 10), the control flow of the above is the same, but because of a change made on the 8th of January (build: Fix QNX CMake build issues), the value that icd_version is initialized to is VK_MAKE_API_VERSION(1, 1, 0, 0), which happens to be the correct version, so the bug stops reproducing.

So, it seems like better logic for that block would be to assume an icd_version of VK_API_VERSION_1_0, unless the scanned icd version is not equal to VK_API_VERSION_1_0, in which case call into icd_enumerate_instance_version -- which should work in my understanding, since vkEnumerateInstanceVersionInfo is present since Vulkan 1.1 and VulkanSC 1.0). Or, maybe just always try to call vkEnumerateInstanceVersion, but set icd_version to VK_API_VERSION_1_0 when GetInstanceProcAddr for that function fails.

**Comment by aqnuep** [comment]
Thanks for the clarification and that makes sense now.

> icd_term->scanned_icd->api_version >= VK_API_VERSION_1_1 evaluates to false (because the version string has no variant value, so it's equal to VK_API_VERSION_1_0), so the if-block is never executed

This one is indeed something that we've overlooked before, so the patch I have in the branch or another way to trigger this path would still make sense, so I'll make sure that's going to be taken for Vulkan SC.

In any case I can take it from here and thank you very much for your input!

**Comment by zangold** [comment]
Thanks! Closing this PR.

**Pull request closed without merging**
